services:
  app:
    build: .
    container_name: nestjs_app
    env_file:
      - .env  # .env 파일을 명시적으로 참조
    volumes:
      - .:/usr/src/app  # 프로젝트 소스를 컨테이너로 마운트
      - /usr/src/app/node_modules  # node_modules는 도커 내부에서만 관리
    ports:
      - "3000:3000"
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # 루트 디렉토리의 postgres_data에 데이터 저장
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: nestjs_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data  # 루트 디렉토리의 redis_data에 데이터 저장
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
