name: portfolio
description: "project json web token"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #Core
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0

  #Network
  dio: ^5.7.0
  jwt_decoder: ^2.0.1

  #Freezed
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  #Serializable
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  #Storage
  flutter_secure_storage: ^9.2.2

  #UI
  cupertino_icons: ^1.0.8

  #Utils
  build_runner: ^2.4.12
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true